using System;
using System.Collections.Generic;
using System.Text;

namespace MacMickey.DomainModel
{
    public class Bread
    {
        /// <summary>
        /// Primary key of bread table
        /// (Autogenerated)
        /// </summary>
        public int BreadId { get; set; }

        /// <summary>
        /// Name of the bread
        /// </summary>
        /// <remarks>50 chars max</remarks>
        /// <example>pain aux céreales, pain aux sésames...</example>
        public string Name { get; set; }

        /// <summary>
        /// Used to prevent sesame allergy
        /// </summary>
        public bool HasSesameSeed { get; set; }

        /// <summary>
        /// Each burger has only one bread, and a bread is used on only one burger (one-to-one relation)
        /// </summary>
        public virtual Burger Burger { get; set; }

        // EF core 2
        /// <summary>
        /// Suppliers of the bread
        /// </summary>
        /// <remarks>Required relationship</remarks>
        public virtual ICollection<BakerBread> BakerBreads { get; set; }
    }
}
